"use client";

export default function DisclaimerPage() {
  return (
    <main style={{ padding: "40px", maxWidth: "900px", margin: "0 auto", lineHeight: "1.6" }}>
      <h1>Medical Disclaimer</h1>

      <p>
        Smart Baby System provides informational insights only.
      </p>

      <p>
        This application is NOT a medical device and does NOT provide medical advice,
        diagnosis, or treatment.
      </p>

      <p>
        All recommendations and insights generated by the system, including AI-based outputs,
        are intended for general informational purposes only.
      </p>

      <p>
        Always consult a qualified doctor or pediatrician regarding your child’s health,
        nutrition, or development.
      </p>

      <p>
        Use of this application is entirely at your own risk.
      </p>
    </main>
  );
}